// Mock database layer — replace with your actual DB (Prisma, Supabase, etc.)
import { Product } from '@/types/product.types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Gold Statement Necklace',
    slug: 'gold-statement-necklace',
    description: 'Elegant gold-plated statement necklace with intricate beadwork, perfect for special occasions.',
    price: 8500,
    compareAtPrice: 12000,
    images: ['/images/products/necklace.jpg'],
    category: 'accessories',
    tags: ['gold', 'necklace', 'statement', 'jewelry'],
    stock: 20,
    sku: 'ACC-NEK-001',
    rating: 4.7,
    reviewCount: 89,
    featured: true,
    isNew: true,
    isSale: true,
    createdAt: '2025-12-01T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Strappy Block Heel',
    slug: 'strappy-block-heel',
    description: 'Comfortable strappy block heel sandals in nude, perfect for all-day wear.',
    price: 11500,
    compareAtPrice: 15000,
    images: ['/images/products/heel.jpg'],
    category: 'footwear',
    tags: ['heel', 'strappy', 'block-heel', 'nude'],
    stock: 15,
    sku: 'FW-HEEL-002',
    rating: 4.5,
    reviewCount: 56,
    featured: true,
    isNew: true,
    isSale: true,
    createdAt: '2025-11-15T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Lace Front Body Wave Wig',
    slug: 'lace-front-body-wave-wig',
    description: 'Premium lace front wig with natural body wave texture, 180% density.',
    price: 45000,
    images: ['/images/products/wig.jpg'],
    category: 'wigs-hair',
    tags: ['wig', 'lace-front', 'body-wave', 'human-hair'],
    stock: 8,
    sku: 'WH-LFW-003',
    rating: 4.9,
    reviewCount: 112,
    featured: true,
    isNew: true,
    isSale: false,
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
  {
    id: '4',
    name: 'Structured Mini Tote',
    slug: 'structured-mini-tote',
    description: 'Elegant structured mini tote bag in premium vegan leather with gold hardware.',
    price: 16000,
    compareAtPrice: 22000,
    images: ['/images/products/tote.jpg'],
    category: 'handbags',
    tags: ['handbag', 'tote', 'mini', 'vegan-leather'],
    stock: 12,
    sku: 'HB-TOT-004',
    rating: 4.6,
    reviewCount: 78,
    featured: true,
    isNew: false,
    isSale: true,
    createdAt: '2025-10-20T00:00:00Z',
    updatedAt: '2025-12-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Matte Liquid Lipstick Set',
    slug: 'matte-liquid-lipstick-set',
    description: 'Set of 5 long-lasting matte liquid lipsticks in nude and berry tones.',
    price: 6500,
    images: ['/images/products/lipstick.jpg'],
    category: 'beauty',
    tags: ['lipstick', 'matte', 'beauty', 'makeup'],
    stock: 30,
    sku: 'BT-LIP-005',
    rating: 4.8,
    reviewCount: 145,
    featured: false,
    isNew: true,
    isSale: false,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Pearl Drop Earings',
    slug: 'pearl-drop-earrings',
    description: 'Classic freshwater pearl drop earrings with gold-filled hooks.',
    price: 5500,
    compareAtPrice: 8000,
    images: ['/images/products/earrings.jpg'],
    category: 'accessories',
    tags: ['pearl', 'earrings', 'gold', 'classic'],
    stock: 25,
    sku: 'ACC-EAR-006',
    rating: 4.9,
    reviewCount: 67,
    featured: false,
    isNew: false,
    isSale: true,
    createdAt: '2025-09-10T00:00:00Z',
    updatedAt: '2025-11-20T00:00:00Z',
  },
];

export async function getProducts() {
  return mockProducts;
}

export async function getProductBySlug(slug: string) {
  return mockProducts.find((p) => p.slug === slug) || null;
}
